// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl-z6ss9OZ_EWeVGpBcIzDSz8-WpECOmk',
    appId: '1:825501669128:web:6d80694b4fd08bdc193ebd',
    messagingSenderId: '825501669128',
    projectId: 'medicare-2fb52',
    authDomain: 'medicare-2fb52.firebaseapp.com',
    storageBucket: 'medicare-2fb52.firebasestorage.app',
    measurementId: 'G-LBFNECNJX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx3dKXaopf4skE0RMl8jhSe3K6VNAKhCI',
    appId: '1:825501669128:android:5c0ccba4676ecc28193ebd',
    messagingSenderId: '825501669128',
    projectId: 'medicare-2fb52',
    storageBucket: 'medicare-2fb52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyIIXSJmY6bp4YR_P_UY_jiY5sf66nbs',
    appId: '1:825501669128:ios:299d15aaa2c221ac193ebd',
    messagingSenderId: '825501669128',
    projectId: 'medicare-2fb52',
    storageBucket: 'medicare-2fb52.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyIIXSJmY6bp4YR_P_UY_jiY5sf66nbs',
    appId: '1:825501669128:ios:299d15aaa2c221ac193ebd',
    messagingSenderId: '825501669128',
    projectId: 'medicare-2fb52',
    storageBucket: 'medicare-2fb52.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl-z6ss9OZ_EWeVGpBcIzDSz8-WpECOmk',
    appId: '1:825501669128:web:359e7c74376ac0ef193ebd',
    messagingSenderId: '825501669128',
    projectId: 'medicare-2fb52',
    authDomain: 'medicare-2fb52.firebaseapp.com',
    storageBucket: 'medicare-2fb52.firebasestorage.app',
    measurementId: 'G-WM1KGG8YNX',
  );
}
